# v4. Удаление кеша apt и pip после установки зависимостей
# NB: зафиксирована базовая версия python:3.12.1 (python:latest = 3.14 несовместим с psycopg2==2.9.9)
FROM python:3.12.1
# -- Медленные операции --
# Установка системных зависимостей (в т.ч. для зависимостей python)
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc \
    && rm -rf /var/lib/apt/lists/*
# Установка зависимостей python
RUN --mount=type=bind,source=requirements.txt,target=/app/requirements.txt \
    pip install --no-cache-dir --no-deps -r /app/requirements.txt
# -- Быстрые операции --
# Копирование кода приложения
COPY app.py /app/
# Установка рабочей директории
WORKDIR /app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0"]
