# v2. Сортировка слоёв: сначала редко изменяемые операции, потом часто изменяемые
# NB: зафиксирована базовая версия python:3.12.1 (python:latest = 3.14 несовместим с psycopg2==2.9.9)
FROM python:3.12.1
# -- Редко изменяемые операции --
# Установка системных зависимостей (в т.ч. для зависимостей python)
RUN apt-get update \
    && apt-get install -y gcc
# Копирование зависимостей python
COPY requirements.txt /app/
# Установка зависимостей python
RUN pip install -r /app/requirements.txt
# -- Часто изменяемые операции --
# Копирование кода приложения
COPY . /app/
# Установка рабочей директории
WORKDIR /app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0"]
